pipeline {
    agent any

    parameters {
        base64File(name: 'UPLOAD', description: 'Upload a file to process')
    }

    stages {
        stage('Receive File') {
            steps {
                withFileParameter('UPLOAD') {
                    sh 'cp $UPLOAD received_file.txt'
                }
                sh 'ls -la'
                sh 'find . -name "*.py"'
            }
        }

        stage('Process File') {
            steps {
                sh 'python3 lab3/script.py received_file.txt processed_file.txt'
            }
        }

        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'processed_file.txt'
            }
        }
    }
}